### PR TITLE
delete unnecessary data

### PR DESCRIPTION
**Pull request by pxtrez**

### CODE REVIEW

**Review by nei7 — CHANGES_REQUESTED** [review]
Just tested and part with sending text to websocket doesn't seem to work

**Comment by pxtrez** [comment]
As I tested it worked, it may work differently in some quizzes.

**Comment by nei7** [comment]
> As I tested it worked, it may work differently in some quizzes.

So, after doing a little more testing on your changes I noticed that even though you don't see new players in the pre-game state, the player count is increasing.
Screenshot-20210929144044-1157x402

After the game started, the list of players appeared:
Screenshot-20210929144202-1082x616

I haven't checked, but it seems that sending incomplete data causes an error on client side in quizizz. I think I'd rather keep my old code here, for better effect. Anyway thanks for suggestion.

**Comment by nei7** [comment]
closing due to inactivity

**Pull request closed without merging**
